Fix for backport of Dell OS10 driver
stackhpc/kayobe pull request #19
Opened 2022-06-30 20:25 UTC by oneswig

Resolves the error:
{"changed": false, "msg": "path specified in src not found"}

2022-07-19 08:36 UTC, markgoddard requested changes

2022-07-19 08:36 UTC, markgoddard commented on ansible/roles/dell-switch/tasks/main.yml
> +    src: dellos10-config.j2
This doesn't match the upstream code, and would result in passing a jinja2 template to the module, rather than the templated output.

2022-08-05 10:28 UTC, priteau commented on ansible/roles/dell-switch/tasks/main.yml
> +    src: dellos10-config.j2
@oneswig could you please check?

2024-11-04 15:48 UTC, priteau commented
I am closing this old pull request for an inactive branch.

2024-11-04 15:48 UTC, closed without merging