Backport selinux change from zed
stackhpc/kayobe pull request #204
Opened 2023-11-14 20:00 UTC by priteau

The disable-selinux role has been renamed to selinux and now supports setting desired state.

Previously Kayobe was defaulting to disabling and rebooted the host - to avoid audit logs filling up. This change allows operators to define desired SELinux state and defaults to permissive - to adhere to those site policies that require SELinux to be at least in permissive state.

Note: unlike the original patch, this backport keeps the default selinux state as disabled.

Change-Id: I42933b0b7d55c69c9f6992e331fafb2e6c42d4d1 (cherry picked from commit caa7cc54ee5919b1b74dcdff21850051641eb9b5)

2023-11-15 09:38 UTC, markgoddard requested changes

2023-11-15 09:38 UTC, markgoddard commented on ansible/roles/selinux/defaults/main.yml
> +selinux_do_reboot: false
How about this to retain backwards compat?
```suggestion
# Whether to reboot to apply SELinux config changes.
disable_selinux_do_reboot: true
selinux_do_reboot: "{{ disable_selinux_do_reboot }}"
```

2023-11-15 09:38 UTC, markgoddard commented on ansible/selinux.yml
> +      selinux_reboot_timeout: "{{ 600 if ansible_facts.virtualization_role == 'host' else 300 }}"
```suggestion
      selinux_reboot_timeout: "{{ disable_selinux_reboot_timeout | default(600 if ansible_facts.virtualization_role == 'host' else 300) }}"
```

2023-11-17 09:07 UTC, markgoddard approved these changes

2023-11-17 09:22 UTC, MoteHue approved these changes

2023-11-17 09:42 UTC, MoteHue commented
Merging now so I can use at AZ

2023-11-17 09:42 UTC, merged